package domain

case class Player(
    assist_free_kick_won: Int = 0,
    stand_catch: Int = 0,
    dangerous_play: Int = 0,
    second_goal_assist: Int = 0,
    assist_own_goal: Int = 0,
    total_sub_on: Int = 0,
    pts_gained_losing_pos: Int = 0,
    dive_save: Int = 0,
    assist_penalty_won: Int = 0,
    game_started: Int = 0,
    offside_provoked: Int = 0,
    assist_handball_won: Int = 0,
    was_fouled: Int = 0,
    assist_pass_lost: Int = 0,
    dive_catch: Int = 0,
    assist_attempt_saved: Int = 0,
    formation_used: Int = 0,
    mins_played: Int = 0,
    head_pass: Int = 0,
    six_second_violation: Int = 0,
    assist_post: Int = 0,
    turnover: Int = 0,
    clean_sheet: Int = 0,
    formation_place: Int = 0,
    yellow_card: Int = 0,
    red_card: Int = 0,
    pts_dropped_winning_pos: Int = 0,
    total_sub_off: Int = 0,
    stand_save: Int = 0,
    assist_blocked_shot: Int = 0,
    first_half_goals: Int = 0,
    back_pass: Int = 0,
    gk_smother: Int = 0,
    keeper_pick_up: Int = 0,
    fouls: Int = 0,
    cross_not_claimed: Int = 0
)
